import { Book } from "@/types/book";
export const mockBookList: Book[] = [
    {
        id: 1,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1586722975l/2767052.jpg",
        rating: 4.3,
    },
    {
        id: 2,
        title: "1984",
        author: "George Orwell",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546910265l/2.jpg",
        rating: 4.5,
    },
    {
        id: 3,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1325861570l/170448.jpg",
        rating: 4.8,
    },
];

export const mockBookCarouselList: Book[] = [
    {
        id: 1,
        title: "The Great Gatsby",
        author: "F. Scott Fitzgerald",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1586722975l/2767052.jpg",
        rating: 4.3,
    },
    {
        id: 2,
        title: "1984",
        author: "George Orwell",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546910265l/2.jpg",
        rating: 4.5,
    },
    {
        id: 3,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1325861570l/170448.jpg",
        rating: 4.8,
    },
    {
        id: 4,
        title: "Pride and Prejudice",
        author: "Jane Austen",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1320399351l/1885.jpg",
        rating: 4.2,
    },
    {
        id: 5,
        title: "The Catcher in the Rye",
        author: "J.D. Salinger",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1398034300l/5107.jpg",
        rating: 3.9,
    },
    {
        id: 6,
        title: "Moby-Dick",
        author: "Herman Melville",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1327940656l/153747.jpg",
        rating: 4.1,
    },
    {
        id: 7,
        title: "War and Peace",
        author: "Leo Tolstoy",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1413215930l/656.jpg",
        rating: 4.6,
    },
    {
        id: 8,
        title: "Crime and Punishment",
        author: "Fyodor Dostoevsky",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546910265l/2.jpg",
        rating: 4.4,
    },
    {
        id: 9,
        title: "Brave New World",
        author: "Aldous Huxley",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546910265l/2.jpg",
        rating: 4.0,
    },
    {
        id: 10,
        title: "The Hobbit",
        author: "J.R.R. Tolkien",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546071216l/5907.jpg",
        rating: 4.7,
    },
    {
        id: 11,
        title: "Fahrenheit 451",
        author: "Ray Bradbury",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546910265l/2.jpg",
        rating: 4.2,
    },
    {
        id: 12,
        title: "Jane Eyre",
        author: "Charlotte Brontë",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1327867269l/10210.jpg",
        rating: 4.3,
    },
    {
        id: 13,
        title: "Wuthering Heights",
        author: "Emily Brontë",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1388212715l/6185.jpg",
        rating: 4.0,
    },
    {
        id: 14,
        title: "The Picture of Dorian Gray",
        author: "Oscar Wilde",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1546910265l/2.jpg",
        rating: 4.1,
    },
    {
        id: 15,
        title: "Dracula",
        author: "Bram Stoker",
        image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1387151694l/17245.jpg",
        rating: 4.3,
    },
];